# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zotero', '0002_auto_20160808_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoteroAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8, unique=True)),
                ('attachment', models.FileField(blank=True, upload_to=b'zotero/')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zotero.ZoteroReference')),
            ],
        ),
    ]
